version: '3'

services:
  db:
    image: mysql
    container_name: db
    restart: always
    env_file: .env
    volumes: 
      - db:/var/lib/mysql
  wordpress:
    depends_on: 
      - db
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - src:/var/www/html
  web:
    depends_on:
      - wordpress
    image: nginx
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - data:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d/default.conf
      - certbot:/etc/letsencrypt
  certbot:
    depends_on:
      - web
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot:/etc/letsencrypt
      - data:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email sample.mail@gmail.com --agree-tos --no-eff-email --staging -d demo.com -d www.demo.com
